// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrmn8QlZOOXYlGm3dhUqWlgtemUj3locs',
    appId: '1:445891986366:web:13d88dac469354e3e9efef',
    messagingSenderId: '445891986366',
    projectId: 'asynconf2026-42509',
    authDomain: 'asynconf2026-42509.firebaseapp.com',
    storageBucket: 'asynconf2026-42509.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK9wUMWx-oVG3jVRaBA940LARaGN5jOJ0',
    appId: '1:445891986366:android:2d95356b18b499c1e9efef',
    messagingSenderId: '445891986366',
    projectId: 'asynconf2026-42509',
    storageBucket: 'asynconf2026-42509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulMpf2g1EFyFOWryQFQDGwQY5dNZApKI',
    appId: '1:445891986366:ios:a67030c12c00677fe9efef',
    messagingSenderId: '445891986366',
    projectId: 'asynconf2026-42509',
    storageBucket: 'asynconf2026-42509.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulMpf2g1EFyFOWryQFQDGwQY5dNZApKI',
    appId: '1:445891986366:ios:a67030c12c00677fe9efef',
    messagingSenderId: '445891986366',
    projectId: 'asynconf2026-42509',
    storageBucket: 'asynconf2026-42509.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrmn8QlZOOXYlGm3dhUqWlgtemUj3locs',
    appId: '1:445891986366:web:c42ad36d3c9d5221e9efef',
    messagingSenderId: '445891986366',
    projectId: 'asynconf2026-42509',
    authDomain: 'asynconf2026-42509.firebaseapp.com',
    storageBucket: 'asynconf2026-42509.firebasestorage.app',
  );
}
